# Generated by Django 3.2.13 on 2023-07-30 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynaconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='group',
            field=models.CharField(default='DEFAULT', max_length=100, validators=[django.core.validators.RegexValidator(message='Group can only contains uppercase letters, numbers and _', regex='[A-Z\\d_]+')]),
        )
    ]
